/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package parkingsystem;
import java.awt.GridLayout;
import java.awt.Color;
import java.util.ArrayList;
/**
 *
 * @author user
 */
public class plotDiagram extends javax.swing.JFrame {

    /** Creates new form plotDiagram */
    public plotDiagram() {
        initComponents();
    }
    
    public plotDiagram( String title, int nRows, int nCols) {
        initComponents();
        this.setTitle(title);
        this.setLayout(new GridLayout(nRows,nCols,10,10));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plotDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plotDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plotDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plotDiagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plotDiagram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
    public void displayParkingLot(int nRows, int nCols, ArrayList<ArrayList<parkingSlot> > ParkingLot) {
        for( int i = 0; i < nRows; i++) {
            for( int j = 0; j < nCols; j++) {
                javax.swing.JPanel parkingPanel = new javax.swing.JPanel();
                if(ParkingLot.get(i).get(j).filled) {
                    parkingPanel.setBackground(Color.red);
                } else {
                    parkingPanel.setBackground(Color.green);
                }
                this.add(parkingPanel);
            }
        }
    }
    
    public void displayAvailableSlots(int nRows, int nCols, ArrayList<ArrayList<parkingSlot> > ParkingLot) {
        for( int i = 0; i < nRows; i++) {
            for( int j = 0; j < nCols; j++) {
                javax.swing.JPanel parkingPanel = new javax.swing.JPanel();
                if(ParkingLot.get(i).get(j).filled) {
                    parkingPanel.setBackground(Color.WHITE);
                } else {
                    parkingPanel.setBackground(Color.green);
                }
                this.add(parkingPanel);
            }
        }
    }
    
    public void displayOccupiedSlots(int nRows, int nCols, ArrayList<ArrayList<parkingSlot> > ParkingLot) {
        for( int i = 0; i < nRows; i++) {
            for( int j = 0; j < nCols; j++) {
                javax.swing.JPanel parkingPanel = new javax.swing.JPanel();
                if(ParkingLot.get(i).get(j).filled) {
                    parkingPanel.setBackground(Color.red);
                } else {
                    parkingPanel.setBackground(Color.WHITE);
                }
                this.add(parkingPanel);
            }
        }
    }
}
